### PR TITLE
Log based on registry known-support - reduce noise on notifications

### LINKED ISSUE #715: Log "Spam": "Could not do a head request
**Describe the bug**
I recently updated to the latest watchtower version. But now I seem to get spammed with the error message:

```
Could not do a head request, falling back to regular pull.
```

which gets logged as well as creates an email notification every time.

**To Reproduce**
1. Updated watchtower to latest image
2. Deploy a container from a gitlab hosted registry
3. Let it run
4. Monitor logs and emails

**Expected behavior**
Ether a way to disable email notifications in case of this error. Or a fix for why the HEAD request is failing.

**Environment**
 - Platform: Ubuntu (Linux)
 - Architecture: x86_64
 - Docker version: 19.03.13, build 4484c46d9d

<details>
<summary><b>Logs from running watchtower with the <code>--debug</code> option</b></summary>

```
2020-12-20T22:04:01Z [I] Running a one time update.
2020-12-20T22:04:01Z [D] Checking containers for updated images
2020-12-20T22:04:01Z [D] Retrieving running containers
2020-12-20T22:04:01Z [D] Trying to load authentication credentials.
                         container: /play-for-today-website
                         image: registry.gitlab.com/***/website:latest
2020-12-20T22:04:01Z [D] Loaded auth credentials for user gitlab+deploy-token-32212, on registry registry.gitlab.com/***/website:latest, from file /config.json
2020-12-20T22:04:01Z [D] Got image name: registry.gitlab.com/***/website:latest
2020-12-20T22:04:01Z [D] Credentials loaded
2020-12-20T22:04:01Z [D] Checking if pull is needed
                         container: /play-for-today-website
                         image: registry.gitlab.com/***/website:latest
2020-12-20T22:04:01Z [D] Building challenge URL
                         URL: https://registry.gitlab.com/v2/
2020-12-20T22:04:02Z [D] Got response to challenge request
                         header: Bearer realm="https://gitlab.com/jwt/auth",service="container_registry"
                         status: 401 Unauthorized
2020-12-20T22:04:02Z [D] Checking challenge header content
                         realm: https://gitlab.com/jwt/auth
                         service: container_registry
2020-12-20T22:04:02Z [D] Setting scope for auth token
                         image: registry.gitlab.com/***/website
                         scope: repository:registry.gitlab.com/***/website:pull
2020-12-20T22:04:02Z [D] Credentials found.
                         credentials: ******
2020-12-20T22:04:02Z [D] Parsing image ref
                         host: registry.gitlab.com
                         image: cogindo/***/website
                         normalized: registry.gitlab.com/***/website:latest
                         tag: latest
2020-12-20T22:04:02Z [D] Doing a HEAD request to fetch a digest
                         url: https://registry.gitlab.com/v2/***/website/manifests/latest
2020-12-20T22:04:02Z [I] Could not do a head request, falling back to regular pull.
2020-12-20T22:04:02Z [D] Reason: registry responded to head request with 401
2020-12-20T22:04:02Z [D] Pulling image
                         container: /play-for-today-website
                         image: registry.gitlab.com/***/website:latest
2020-12-20T22:04:04Z [D] No new images found for /play-for-today-website

```

</details>

**Additional context**

The issue seem to happen only for the gitlab registry. Maybe that helps fixing it.

### PR DESCRIPTION
**Pull request by tkalus**
Some private registries do not support HEAD (E.G. GitLab Container Registry).
With the current config, this log message is causing a notification to be
sent for each container hosted in a registry lacking HEAD support.

Attempt to `log.Debug` or `log.Warning` for failed HTTP HEAD-check based on
registry hostname.  For Docker Hub, a failed HEAD may count against a
user's call-quota whereas other registry implementations do not support HEAD.

Fixes #715

### CODE REVIEW

**Comment by tkalus** [comment]
In my case, I'm getting 48 noop notifications per hour:
- three containers in GitLab Container Registry
- two identical VMs behind a LB for HA
- 15 minute checks
- email and Slack notifications

I'm _hoping_ this is in time for the next tagged release -- and that it's soon.

**Comment by simonaronsson** [comment]
Hi,

Thank you for your contribution! We'll definitely consider this in case we're unable to get HEAD to work consistently. However, I'd like to wait for `v1.1.1` to be rolled out first to see how many false positives we actually get post that.

In the best of worlds, we'll be able to keep logs of failing head requests as a warning for when DockerHub users are consuming their rate limit - without spamming you in the progress.

If it's still too noisy post that, and we come to the conclusion that we're out of options, we'll make a fast patch release with your changes.

Best,
Simme

**Comment by tkalus** [comment]
Hey @simskij, thanks for the consideration.

Totally agree with the need for visibility when it comes to Docker Hub API consumption -- and I half-agree with the idea of checking HEAD only on dockerhub.

I'll bring it up in issue 715 too, but one idea might be _keep_ the check for all containers/registries but selectively `log.Debug()` or `log.Warning()` based on the registry hostname?

**Comment by tkalus** [comment]
Updated with one _possible_ way.  Golang isn't my one of my primary languages, so I'm not going to feel bad at all if this isn't up to y'alls standards or deviates too far from the established patterns.

I managed to confirm it works by dint of live testing.

Here are the relevant log files with some light redaction:
```
watchtower    | time="2020-12-22T00:28:35Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/tkalus-forks/watchtower/manifests/latest"
watchtower    | time="2020-12-22T00:28:35Z" level=warning msg="Could not do a head request, falling back to regular pull." container=/watchtower image="tkalus-forks/watchtower:latest"
watchtower    | time="2020-12-22T00:28:35Z" level=debug msg="Reason: registry responded to head request with &{401 Unauthorized 401 HTTP/1.1 1 1 map[Content-Length:[166] Content-Type:[application/json] Date:[Tue, 22 Dec 2020 00:28:35 GMT] Docker-Distribution-Api-Version:[registry/2.0] Strict-Transport-Security:[max-age=31536000] Www-Authenticate:[Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:tkalus-forks/watchtower:pull\",error=\"insufficient_scope\"]] {} 166 [] false false map[] 0xc000432c00 0xc00044c4d0}"
watchtower    | time="2020-12-22T00:28:35Z" level=debug msg="Pulling image" container=/watchtower image="tkalus-forks/watchtower:latest"
watchtower    | time="2020-12-22T00:28:36Z" level=debug msg="Error pulling image tkalus-forks/watchtower:latest, Error response from daemon: pull access denied for tkalus-forks/watchtower, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
watchtower    | time="2020-12-22T00:28:36Z" level=info msg="Unable to update container \"/watchtower\": Error response from daemon: pull access denied for tkalus-forks/watchtower, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next."
...
watchtower    | time="2020-12-22T00:28:37Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://registry.gitlab.com/v2/<snip:gitlab_org>/<snip:gitlab_repo>/manifests/latest"
watchtower    | time="2020-12-22T00:28:37Z" level=debug msg="Could not do a head request, falling back to regular pull."
watchtower    | time="2020-12-22T00:28:37Z" level=debug msg="Reason: registry responded to head request with &{401 Unauthorized 401 HTTP/1.1 1 1 map[Content-Length:[160] Content-Type:[application/json] Date:[Tue, 22 Dec 2020 00:28:37 GMT] Docker-Distribution-Api-Version:[registry/2.0] Www-Authenticate:[Bearer realm=\"https://gitlab.com/jwt/auth\",service=\"container_registry\",scope=\"repository:<snip:gitlab_org>/<snip:gitlab_repo>:pull\",error=\"insufficient_scope\"] X-Content-Type-Options:[nosniff]] {} 160 [] false false map[] 0xc000433e00 0xc00044cf20}"
watchtower    | time="2020-12-22T00:28:37Z" level=debug msg="Pulling image" container=/<snip:gitlab_repo> image="registry.gitlab.com/<snip:gitlab_org>/<snip:gitlab_repo>:latest"
watchtower    | time="2020-12-22T00:28:38Z" level=debug msg="No new images found for /<snip:gitlab_repo>"
...
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/library/traefik/manifests/v2.1"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg="Found a remote digest to compare with" remote="sha256:ab83baa3d198ee5a2fd685bed96417055a2bdd271efe11a0b831d6c02436aabd"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg=Comparing local="sha256:2c17c789b4913f29d1f64199cc3d9110f77fc3f7d6bafb306520d9e377efff96" remote="sha256:ab83baa3d198ee5a2fd685bed96417055a2bdd271efe11a0b831d6c02436aabd"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg=Comparing local="sha256:ab83baa3d198ee5a2fd685bed96417055a2bdd271efe11a0b831d6c02436aabd" remote="sha256:ab83baa3d198ee5a2fd685bed96417055a2bdd271efe11a0b831d6c02436aabd"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg="Found a match"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg="No pull needed. Skipping image."
```

The error on the 'full-pull' for `tkalus-forks/watchtower` is expected -- and demonstrates the reduced noise v. desired alerting nicely.

File: pkg/registry/registry.go [hunk 1]
```diff
@@ -31,3 +34,23 @@ func DefaultAuthHandler() (string, error) {
...
+	if err != nil {
+		return false
+	}
+
+	containerHost, err := helpers.NormalizeRegistry(normalizedName.String())
+	if err != nil {
+		return false
+	}
+
+	if containerHost == "index.docker.io" {
```
Comment (simonaronsson) [inline pkg/registry/registry.go]: This should also include ghcr.io

File: pkg/container/client.go [hunk 2]
```diff
@@ -295,7 +295,11 @@ func (client dockerClient) PullImage(ctx context.Context, container Container) e
 	log.WithFields(fields).Debugf("Checking if pull is needed")
 
 	if match, err := digest.CompareDigest(container, opts.RegistryAuth); err != nil {
-		log.Info("Could not do a head request, falling back to regular pull.")
+		if registry.WarnOnAPIComsumption(container) {
```
Comment (simonaronsson) [inline pkg/container/client.go]:
```suggestion
		if registry.WarnOnAPIConsumption(container) {
```

File: pkg/registry/registry.go [hunk 3]
```diff
@@ -31,3 +34,23 @@ func DefaultAuthHandler() (string, error) {
 	log.Debug("Authentication request was rejected. Trying again without authentication")
 	return "", nil
 }
+
+// WarnOnAPIComsumption will return true if the registry is knonw-expected to respond to HTTP HEAD in checking the container digest; will return false if behavior is unknown.
+func WarnOnAPIComsumption(container watchtowerTypes.Container) bool {
```
Comment (simonaronsson) [inline pkg/registry/registry.go]:
```suggestion
// WarnOnAPIConsumption will return true if the registry is knonw-expected to respond to HTTP HEAD in checking the container digest; will return false if behavior is unknown.
func WarnOnAPIConsumption(container watchtowerTypes.Container) bool {
```

**Review by simonaronsson — CHANGES_REQUESTED** [review]
Looks really good! Some minor nitpicks, but other than that I think we're ready to roll 👍 🎉 Thanks for helping out! 🙏

**Comment by tkalus** [comment]
@simskij Based on the comments in Issue 715, it seems as though GitLab Registry are the _only_ ones still suffering heartburn.  It appears they have a URL pathname pattern for the manifests that's different from DockerHub, GitHub, GCR, and others.

**Any objection to flipping the logic so it `Warn`s on everything _but_ `registry.gitlab.com`?**

Strange thing is that GitLab Registry _does_ respond appropriately to the command `docker manifest inspect`, so it _is_ able to pull the manifest -- somehow.  I might see about running `docker manifest inspect` through `mitmproxy` to see what pathnames are being pulled if I find some time over my holiday downtime.

**Comment by simonaronsson** [comment]
I think the previous approach with only making them info-level for DockerHub probably will work better, as that's the only case (right now) where it actually makes any real difference for the user. In the other cases, if it works then good, otherwise no harm, right?

My thinking is that we already know of two or three cases where it won't work, GitLab, GitHub Packages, and some local registries. For local registries, I assume the varying success rate mostly has to do with versions and such as it works for me with `registry:2.7`.

**Comment by tkalus** [comment]
Totally reasonable to me.  💯 agree: local, private-network registries will be hard to enumerate and _probably_ shouldn't be notifying anyway.

Will revert and push in just a moment -- `Warn` on `index.docker.io` and `ghcr.io` and `Debug` on others.

**Comment by simonaronsson** [comment]
Awesome! Thanks a bunch for your help with this!

**Comment by simonaronsson** [comment]
@all-contributors add @tkalus for code
