### PR TITLE
Skip updating containers where no local image info can be retrieved

### LINKED ISSUE #584: Portainer Disappeared After Update
**Describe the bug**
WatchTower is configured with --schedule to check daily for updates at 00:00.  I noticed this morning that I couldn't access Portainer, and subsequently discovered that the container was no longer present.

I have all my `docker run -d` commands saved, and volumes mounted for any data, so was able to get Portainer back again within minutes.  

I found the below mentioned logs in WatchTower.

**Expected behavior**
The Portainer container to be recreated with the updated image.

**Environment**
 - Platform = Synology NAS DS1813+
 - Architecture = x86-64
 - Docker version = 19.03.11

**Logs from running watchtower with the `--debug` option**
```
time="2020-06-17T00:00:02+01:00" level=debug msg="Pulling portainerci/portainer:develop for /Portainer"
time="2020-06-17T00:00:02+01:00" level=debug msg="Loaded auth credentials for user ********* on registry portainerci/portainer:develop"
time="2020-06-17T00:00:02+01:00" level=debug msg="Got image name: portainerci/portainer:develop"
time="2020-06-17T00:00:15+01:00" level=info msg="Found new portainerci/portainer:develop image (sha256:ee07cae635877c0e5bd730dff415ea1380b1f3334c896924b1d6cbd6f983ca5a)"
time="2020-06-17T00:00:20+01:00" level=info msg="Stopping /Portainer (d8876b6c4a93813738dc39ed39899acb856b0beb05b7a991111b99c068444433) with SIGTERM"
time="2020-06-17T00:00:21+01:00" level=debug msg="Removing container d8876b6c4a93813738dc39ed39899acb856b0beb05b7a991111b99c068444433"
2020/06/17 00:00:21 cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc00040e190)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:161 +0x9e
panic(0xacd1e0, 0x1127b00)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/containrrr/watchtower/pkg/container.Container.runtimeConfig(0x100, 0xc000316f60, 0x0, 0x0)
	/go/watchtower/pkg/container/container.go:169 +0x4e
github.com/containrrr/watchtower/pkg/container.dockerClient.StartContainer(0xcb4e80, 0xc0002ca700, 0x1, 0x900100, 0xc000316f60, 0x0, 0x1, 0xc000340100, 0xc000316f60, 0x0)
	/go/watchtower/pkg/container/client.go:163 +0x86
github.com/containrrr/watchtower/internal/actions.restartStaleContainer(0x1b550100, 0xc000316f60, 0x0, 0xca5960, 0xc0002d0c00, 0xc0002c7810, 0x1, 0x6fc23ac00, 0x0)
	/go/watchtower/internal/actions/update.go:121 +0xdb
github.com/containrrr/watchtower/internal/actions.restartContainersInSortedOrder(0xc0004ba000, 0x5, 0x8, 0xca5960, 0xc0002d0c00, 0xc0002c7810, 0x1, 0x6fc23ac00, 0x0)
	/go/watchtower/internal/actions/update.go:96 +0x241
github.com/containrrr/watchtower/internal/actions.Update(0xca5960, 0xc0002d0c00, 0xc0002c7810, 0x1, 0x6fc23ac00, 0x0, 0xed679f761, 0x2000300010000)
	/go/watchtower/internal/actions/update.go:53 +0x37a
github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0xc0002c7810)
	/go/watchtower/cmd/root.go:206 +0xbe
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule.func1()
	/go/watchtower/cmd/root.go:163 +0xb6
github.com/robfig/cron.FuncJob.Run(0xc0004056a0)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:92 +0x25
github.com/robfig/cron.(*Cron).runWithRecovery(0xc00040e190, 0xc8f160, 0xc0004056a0)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:165 +0x59
created by github.com/robfig/cron.(*Cron).run
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:199 +0x747
```

**Additional context**
Image = `containrrr/watchtower:latest-dev`

### PR DESCRIPTION
**Pull request by piksel**
Partially reverts containrrr/watchtower#571, since it causes `dockerClient.StartContainer()` to crash since it uses `imageInfo` to rebuild the config.

Fixes #584

### CODE REVIEW

**Comment by tammert** [comment]
Won't this reintroduce #215 though? In the situation where the running container uses an image that it not available locally (anymore).

**Comment by simonaronsson** [comment]
@tammert 
> Won't this reintroduce #215 though? In the situation where the running container uses an image that it not available locally (anymore).

It might very well do that, however - it will still grab `oldImageID` from `ContainerJSONBase`, which I think is the crucial part of your previous fix, right?

What happens right now, is that all other calls to ImageInfo throughout the code will try to dereference a null pointer, and as a result, crashes watchtower. For instance:

https://github.com/containrrr/watchtower/blob/master/pkg/container/container.go#L166-L208

I think any suggestion as to how to do this differently is welcome, though, as relying on `ImageInfo` seems to be a fragile solution in general.

I'm holding off on approving this review until we've sorted out this discussion. 👍

File: pkg/container/client.go [hunk 1]
```diff
@@ -119,7 +119,12 @@ func (client dockerClient) GetContainer(containerID string) (Container, error) {
 		return Container{}, err
 	}
 
-	container := Container{containerInfo: &containerInfo}
+	imageInfo, _, err := client.api.ImageInspectWithRaw(bg, containerInfo.Image)
```
Comment (tammert) [inline pkg/container/client.go:122]: @simskij the crash found in #215 is actually caused by `client.api.ImageInspectWithRaw`, _not_ by `ContainerJSONBase.Image` -> `container.imageInfo.ID` needs `ImageInspectWithRaw`.

Alternatively, if we handle the error from `ImageInspectWithRaw` properly (a log message along the lines of "The source image for container x is not present locally, cant update, skipping...") we might have the most reasonable solution?

**Comment by osheroff** [comment]
```
anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x150c2be]

goroutine 40 [running]:
github.com/containrrr/watchtower/pkg/container.Container.runtimeConfig(0xc000100100, 0xc0003ffa70, 0x0, 0xc0000fc058)
	/Users/ben/src/watchtower/pkg/container/container.go:169 +0x4e
github.com/containrrr/watchtower/pkg/container.dockerClient.StartContainer(0x18c4d60, 0xc000078800, 0x1, 0x100, 0xc0003ffa70, 0x0, 0x1, 0xc0001e0100, 0x0, 0xc00013ec68)
	/Users/ben/src/watchtower/pkg/container/client.go:163 +0x86
github.com/containrrr/watchtower/internal/actions.restartStaleContainer(0xc061f80100, 0xc0003ffa70, 0x0, 0x18b5600, 0xc00000f940, 0xc000057b30, 0x0, 0x2540be400, 0x0)
	/Users/ben/src/watchtower/internal/actions/update.go:121 +0xdb
github.com/containrrr/watchtower/internal/actions.restartContainersInSortedOrder(0xc0001c3710, 0x2, 0x2, 0x18b5600, 0xc00000f940, 0xc000057b30, 0x0, 0x2540be400, 0x0)
	/Users/ben/src/watchtower/internal/actions/update.go:96 +0x241
github.com/containrrr/watchtower/internal/actions.Update(0x18b5600, 0xc00000f940, 0xc000057b30, 0x0, 0x2540be400, 0x0, 0xc0002b8ed8, 0x1015de3)
	/Users/ben/src/watchtower/internal/actions/update.go:53 +0x37a
github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0xc000057b30)
	/Users/ben/src/watchtower/cmd/root.go:211 +0xbe
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule.func1()
	/Users/ben/src/watchtower/cmd/root.go:168 +0xb0
github.com/robfig/cron/v3.FuncJob.Run(0xc00041b000)
	/Users/ben/src/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x25
github.com/robfig/cron/v3.(*Cron).startJob.func1(0xc0003f7900, 0x189e580, 0xc00041b000)
	/Users/ben/src/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x61
created by github.com/robfig/cron/v3.(*Cron).startJob
	/Users/ben/src/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x73
```

File: internal/actions/update.go [hunk 2]
```diff
@@ -25,11 +26,13 @@ func Update(client container.Client, params types.UpdateParams) error {
 		return err
 	}
 
-	for i, container := range containers {
-		stale, err := client.IsContainerStale(container)
+	for i, targetContainer := range containers {
+		stale, err := client.IsContainerStale(targetContainer)
+		if stale && !params.NoRestart && !params.MonitorOnly && !targetContainer.HasImageInfo() {
+			err = errors.New("container does not have any available image info and cannot be automatically restarted")
```
Comment (simonaronsson) [inline internal/actions/update.go]: Mind changing this to an `Errorf` and include the container name like on line 35?

**Review by simonaronsson — CHANGES_REQUESTED** [review]

File: internal/actions/update.go (hunk 2 above)
Comment (piksel) [reply internal/actions/update.go]: Its handled just beneath and combined with the other situation where updating is skipped. I did shorten the message though, as it becomes quite verbose.

File: pkg/container/client.go (hunk 1 above)
Comment (piksel) [reply pkg/container/client.go:122]: I changed to a warning and then handle imageInfo being nil in `Update`, skipping the container in such an event.

**Review by tammert — APPROVED** [review]
LGTM :+1:
